-- Creating Table Patient

CREATE TABLE PATIENTS (
    PATIENT_ID NUMBER PRIMARY KEY USING INDEX TABLESPACE FEEDBACK_IDX,
    PATIENT_NAME VARCHAR2(100) NOT NULL,
    EMAIL VARCHAR2(100),
    PHONE VARCHAR2(20)
) TABLESPACE FEEDBACK_DATA;

-- Create Table Departments

CREATE TABLE DEPARTMENTS (
    DEPT_ID NUMBER PRIMARY KEY USING INDEX TABLESPACE FEEDBACK_IDX,
    DEPT_NAME VARCHAR2(100) NOT NULL
) TABLESPACE FEEDBACK_DATA;

-- Creating Table Feedbacks

CREATE TABLE FEEDBACK (
    FEEDBACK_ID NUMBER PRIMARY KEY USING INDEX TABLESPACE FEEDBACK_IDX,
    PATIENT_ID NUMBER REFERENCES PATIENTS(PATIENT_ID),
    DEPT_ID NUMBER REFERENCES DEPARTMENTS(DEPT_ID),
    RATING NUMBER(1) CHECK (RATING BETWEEN 1 AND 5),
    COMMENTS VARCHAR2(500),
    FEEDBACK_DATE DATE DEFAULT SYSDATE,
    STATUS VARCHAR2(20) DEFAULT 'PENDING'
) TABLESPACE FEEDBACK_DATA;

-- Creating Table Audit_log

CREATE TABLE AUDIT_LOG (
    AUDIT_ID NUMBER PRIMARY KEY USING INDEX TABLESPACE FEEDBACK_IDX,
    FEEDBACK_ID NUMBER,
    ACTION VARCHAR2(10),
    ACTION_DATE TIMESTAMP DEFAULT SYSTIMESTAMP,
    USER_NAME VARCHAR2(50)
) TABLESPACE FEEDBACK_DATA;

-- Creating Table Holidays

CREATE TABLE HOLIDAYS (
    HOLIDAY_ID NUMBER(5) PRIMARY KEY,
    HOLIDAY_NAME VARCHAR2(100) NOT NULL,
    HOLIDAY_DATE DATE NOT NULL UNIQUE,
    IS_ACTIVE CHAR(1) DEFAULT 'Y'
);
