-- Insert Departments

INSERT INTO DEPARTMENTS (DEPT_ID, DEPT_NAME) VALUES (DEPT_SEQ.NEXTVAL, 'Emergency');
INSERT INTO DEPARTMENTS (DEPT_ID, DEPT_NAME) VALUES (DEPT_SEQ.NEXTVAL, 'Cardiology');
INSERT INTO DEPARTMENTS (DEPT_ID, DEPT_NAME) VALUES (DEPT_SEQ.NEXTVAL, 'Pediatrics');
COMMIT;

-- Insert Patients

INSERT INTO PATIENTS (PATIENT_ID, PATIENT_NAME, EMAIL, PHONE) VALUES (PATIENT_SEQ.NEXTVAL, 'John Smith', 'john@email.com', '0788112233');
INSERT INTO PATIENTS (PATIENT_ID, PATIENT_NAME, EMAIL, PHONE) VALUES (PATIENT_SEQ.NEXTVAL, 'Mary Johnson', 'mary@email.com', '0788445566');
INSERT INTO PATIENTS (PATIENT_ID, PATIENT_NAME, EMAIL, PHONE) VALUES (PATIENT_SEQ.NEXTVAL, 'David Lee', 'david@email.com', '0788778899');
COMMIT;

-- Insert Feedback

INSERT INTO FEEDBACK (FEEDBACK_ID, PATIENT_ID, DEPT_ID, RATING, COMMENTS) VALUES (FEEDBACK_SEQ.NEXTVAL, 1, 1, 5, 'Very quick service in emergency!');
INSERT INTO FEEDBACK (FEEDBACK_ID, PATIENT_ID, DEPT_ID, RATING, COMMENTS) VALUES (FEEDBACK_SEQ.NEXTVAL, 2, 2, 3, 'Doctor was good but waiting time long');
INSERT INTO FEEDBACK (FEEDBACK_ID, PATIENT_ID, DEPT_ID, RATING, COMMENTS) VALUES (FEEDBACK_SEQ.NEXTVAL, 3, 1, 2, 'Waited 3 hours, not good');
COMMIT;

-- Insert Holidays

INSERT INTO HOLIDAYS (HOLIDAY_ID, HOLIDAY_NAME, HOLIDAY_DATE) VALUES (HOLIDAY_SEQ.NEXTVAL, 'Christmas Day', DATE '2025-12-25');
INSERT INTO HOLIDAYS (HOLIDAY_ID, HOLIDAY_NAME, HOLIDAY_DATE) VALUES (HOLIDAY_SEQ.NEXTVAL, 'New Years Day', DATE '2026-01-01');
INSERT INTO HOLIDAYS (HOLIDAY_ID, HOLIDAY_NAME, HOLIDAY_DATE) VALUES (HOLIDAY_SEQ.NEXTVAL, 'Test Holiday', TRUNC(SYSDATE)); -- Today as holiday for testing

COMMIT;
