-- Creating Trigger 1 NO_WEEKEND_UPDATES

CREATE OR REPLACE TRIGGER NO_WEEKEND_UPDATES
 
    BEFORE INSERT OR UPDATE OR DELETE ON FEEDBACK
FOR EACH ROW
DECLARE
    v_day VARCHAR2(10);
BEGIN
    v_day := TO_CHAR(SYSDATE, 'DY');
    IF v_day IN ('SAT', 'SUN') THEN
        RAISE_APPLICATION_ERROR(-20001, 
            'Operation not allowed on weekends. Please try Monday-Friday.');
    END IF;
END NO_WEEKEND_UPDATES;
/

-- Creating Trigger 2 LOG_FEEDBACK_CHANGES

CREATE OR REPLACE TRIGGER LOG_FEEDBACK_CHANGES

    AFTER INSERT OR UPDATE OR DELETE ON FEEDBACK
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        INSERT INTO AUDIT_LOG (AUDIT_ID, FEEDBACK_ID, ACTION, USER_NAME)
        VALUES (AUDIT_SEQ.NEXTVAL, :NEW.FEEDBACK_ID, 'INSERT', USER);
    ELSIF UPDATING THEN
        INSERT INTO AUDIT_LOG (AUDIT_ID, FEEDBACK_ID, ACTION, USER_NAME)
        VALUES (AUDIT_SEQ.NEXTVAL, :NEW.FEEDBACK_ID, 'UPDATE', USER);
    ELSIF DELETING THEN
        INSERT INTO AUDIT_LOG (AUDIT_ID, FEEDBACK_ID, ACTION, USER_NAME)
        VALUES (AUDIT_SEQ.NEXTVAL, :OLD.FEEDBACK_ID, 'DELETE', USER);
    END IF;
END LOG_FEEDBACK_CHANGES;
/

-- Testing Triggers Created above

BEGIN
    ADD_FEEDBACK(1, 2, 4, 'Testing audit trigger');
END;
/

SELECT * FROM AUDIT_LOG;
