-- Department Performance Analysis
SELECT 
    D.DEPT_NAME,
    COUNT(F.FEEDBACK_ID) AS TOTAL_FEEDBACK,
    ROUND(AVG(F.RATING), 2) AS AVG_RATING,
    SUM(CASE WHEN F.RATING >= 4 THEN 1 ELSE 0 END) AS POSITIVE_COUNT,
    SUM(CASE WHEN F.RATING <= 2 THEN 1 ELSE 0 END) AS NEGATIVE_COUNT,
    ROUND((SUM(CASE WHEN F.RATING >= 4 THEN 1 ELSE 0 END) / COUNT(*)) * 100, 2) AS SATISFACTION_PERCENT
FROM DEPARTMENTS D
LEFT JOIN FEEDBACK F ON D.DEPT_ID = F.DEPT_ID
GROUP BY D.DEPT_NAME
ORDER BY AVG_RATING DESC;

-- Monthly Feedback Trends
SELECT 
    TO_CHAR(FEEDBACK_DATE, 'YYYY-MM') AS MONTH,
    COUNT(*) AS FEEDBACK_COUNT,
    AVG(RATING) AS AVG_RATING,
    COUNT(CASE WHEN STATUS = 'PENDING' THEN 1 END) AS PENDING_COUNT,
    COUNT(CASE WHEN STATUS = 'RESOLVED' THEN 1 END) AS RESOLVED_COUNT
FROM FEEDBACK
GROUP BY TO_CHAR(FEEDBACK_DATE, 'YYYY-MM')
ORDER BY MONTH DESC;

-- Rating Distribution Analysis
SELECT 
    RATING,
    COUNT(*) AS COUNT,
    ROUND(COUNT(*) * 100.0 / SUM(COUNT(*)) OVER(), 2) AS PERCENTAGE,
    RPAD('1', COUNT(*) / 2, '1') AS CHART
FROM FEEDBACK
GROUP BY RATING
ORDER BY RATING;
