-- Audit Summary
SELECT 
    ACTION,
    COUNT(*) AS COUNT,
    TO_CHAR(MIN(ACTION_DATE), 'DD-MON') AS FIRST_DATE,
    TO_CHAR(MAX(ACTION_DATE), 'DD-MON') AS LAST_DATE
FROM AUDIT_LOG
GROUP BY ACTION
ORDER BY COUNT DESC;

-- User Activity Audit
SELECT 
    USER_NAME,
    COUNT(*) AS TOTAL_ACTIONS,
    COUNT(CASE WHEN ACTION = 'INSERT' THEN 1 END) AS INSERTS,
    COUNT(CASE WHEN ACTION = 'UPDATE' THEN 1 END) AS UPDATES,
    COUNT(CASE WHEN ACTION = 'DELETE' THEN 1 END) AS DELETES,
    TO_CHAR(MAX(ACTION_DATE), 'DD-MON HH24:MI') AS LAST_ACTION
FROM AUDIT_LOG
GROUP BY USER_NAME
ORDER BY TOTAL_ACTIONS DESC;

-- Daily Audit Report
SELECT 
    TRUNC(ACTION_DATE) AS DAY,
    COUNT(*) AS DAILY_ACTIONS,
    COUNT(CASE WHEN ACTION = 'INSERT' THEN 1 END) AS DAILY_INSERTS,
    COUNT(CASE WHEN ACTION = 'UPDATE' THEN 1 END) AS DAILY_UPDATES
FROM AUDIT_LOG
GROUP BY TRUNC(ACTION_DATE)
ORDER BY DAY DESC;
