-- To get all the feedbacks with details
SELECT 
    F.FEEDBACK_ID,
    P.PATIENT_NAME,
    D.DEPT_NAME,
    F.RATING,
    F.COMMENTS,
    F.STATUS,
    TO_CHAR(F.FEEDBACK_DATE, 'DD-MON-YYYY') AS DATE_GIVEN
FROM FEEDBACK F
JOIN PATIENTS P ON F.PATIENT_ID = P.PATIENT_ID
JOIN DEPARTMENTS D ON F.DEPT_ID = D.DEPT_ID
ORDER BY F.FEEDBACK_DATE DESC;

-- We will use this to get patient feedback count
SELECT 
    P.PATIENT_NAME,
    COUNT(F.FEEDBACK_ID) AS FEEDBACK_COUNT,
    AVG(F.RATING) AS AVG_RATING
FROM PATIENTS P
LEFT JOIN FEEDBACK F ON P.PATIENT_ID = F.PATIENT_ID
GROUP BY P.PATIENT_NAME
ORDER BY FEEDBACK_COUNT DESC;

-- we will also use this to get audit trail
SELECT 
    TO_CHAR(ACTION_DATE, 'DD-MON HH24:MI:SS') AS TIME,
    FEEDBACK_ID,
    ACTION,
    USER_NAME
FROM AUDIT_LOG
ORDER BY ACTION_DATE DESC;
